// Hand-written English + Tagalog/Taglish test messages (none are in src/patterns.js or the training data).
// The last two scams are real Whisper translations of Filipino-voice test calls.
export const FIL_TEST = [
  [1, 'Hi, this is your nephew, I lost my phone. This is my new number. Can you send me 5,000 for the hospital? Please hurry.'],
  [1, 'This is the police. There is a warrant for your arrest. Pay the penalty with bitcoin immediately.'],
  [1, 'Dad, my phone broke, I am texting from a friend. I need you to pay my rent today, I will pay you back next week.'],
  [1, 'Good afternoon, I am calling from Windows technical department, your laptop is sending us error messages, can you turn it on?'],
  [1, 'Join our VIP trading group, our members are making huge profits daily, minimum deposit is only five hundred dollars.'],
  [1, 'Tita, si Mark po ito, bagong number ko. Naaksidente po ako, pwede po bang mag-send kayo ng 5k sa GCash ko? Wag nyo po sabihin kay mama.'],
  [1, 'Congrats! Nanalo ka ng 50,000 pesos sa raffle. Magbayad lang ng processing fee para makuha ang premyo mo.'],
  [1, "Ma'am taga-BDO po ako, may suspicious transaction sa account nyo. Pakibigay po ang OTP na natanggap nyo para ma-cancel."],
  [1, 'Ito ay mula sa pulis. May warrant of arrest kayo. Magbayad kayo ng multa ngayon din o kayo ay aarestuhin.'],
  [1, 'Hiring! Work from home, kikita ka ng 3,000 kada araw. Magbayad lang ng registration fee para makapagsimula.'],
  [1, 'Yung parcel nyo po ay naka-hold sa customs. Bayaran lang po ang delivery fee sa link na ito.'],
  [1, "I am in the proud department. you can also transfer your account and if I freeze it today. Stop! I need your A, the number we sent to your cell phone. Let's speed up and don't tell anyone."],
  [1, "Aunt, this is Mark, your relative. The phone is off. I was in the hospital for an accident. Can you send 5,000 to my cash? Please just urgent, don't tell your mom."],
  [0, 'Hello, this is the clinic, your test results are ready, you can pick them up any time this week.'],
  [0, 'Hi, your bank here. Just letting you know our branch will be closed on the holiday.'],
  [0, 'I paid you back for the concert tickets, check your account.'],
  [0, 'Hello, I am calling about the apartment listing, is it still available for viewing?'],
  [0, 'Hello po Lola, pupunta po kami dyan sa Linggo para sa birthday ni Lolo. Magdadala kami ng pancit.'],
  [0, 'Anak, nakauwi ka na ba? Kumain ka na? Ingat ka sa biyahe.'],
  [0, 'Pare, tuloy ba tayo sa basketball mamaya? Alas singko sa court.'],
  [0, 'Ma, nabayaran ko na yung kuryente. Pakicheck na lang po yung resibo sa email.'],
  [0, 'Good morning po, paalala lang po na may meeting tayo bukas ng alas nuwebe.'],
  [0, 'Naka-schedule po kayo sa dentist sa Huwebes ng alas tres ng hapon.'],
  [0, 'Hello, Grandma. This is Ana. We will go there on a week for the birthday. We will bring a pancit and cake. What time are you free?'],
  [0, "Hey, are we still on for lunch tomorrow? I'll bring the slides for the client meeting."],
];
