// Normal (non-scam) Filipino messages to balance the spam-only Philippine dataset, so the classifier
// doesn't learn "Tagalog = scam". Written by the ScamEar team; covers family, work, errands and legit notifications.
export const PH_NORMAL = [
  'Nak, nakauwi ka na ba? Text mo ako pag nasa bahay ka na.',
  'Ma, late ako uuwi mamaya, may overtime kami sa office.',
  'Pa, pakisundo naman si bunso sa school mamayang alas kwatro.',
  'Tita, salamat po sa pasalubong! Ang sarap po ng ube halaya.',
  'Lola, dadalaw po kami sa Sabado ng hapon. May gusto po ba kayong ipabili?',
  'Kuya, nasaan ka na? Andito na ako sa may jollibee sa tapat ng mall.',
  'Ate, pahiram naman ng charger mo mamaya, naiwan ko yung akin.',
  'Ma, nakapagbayad na ako ng tubig at kuryente. Yung resibo nasa ref.',
  'Anak, wag kalimutan uminom ng gamot mo ha. Ingat ka palagi.',
  'Bro, tuloy ba tayo sa basketball bukas? 6pm sa covered court.',
  'Pare, pasensya na di ako nakasagot kanina, nasa meeting ako.',
  'Happy birthday Tita! Sana marami pang birthday na darating. Love you po!',
  'Merry Christmas po sa inyong lahat! Kita kits sa noche buena.',
  'Ingat kayo sa biyahe pauwi ng probinsya. Text kayo pag nakarating na.',
  'Ma, nakarating na ako sa dorm. Okay naman ang biyahe.',
  'Sino may extra payong? Ang lakas ng ulan dito sa Cubao.',
  'Pakidala na lang yung tupperware ni Mama pag punta mo dito.',
  'Uwi ka ba this weekend? Magluluto si Mama ng sinigang.',
  'Natanggap ko na yung padala mo, salamat ha. Pambili ng gamot ni Lolo.',
  'Nag-send na ako ng pambayad sa tuition, check mo na lang sa app.',
  'Hi sir, good morning po. Papasok po ako ng 10am, may check-up lang po ako.',
  'Ma\'am, natapos ko na po yung report. Na-email ko na po sa inyo.',
  'Team, reminder lang na may meeting tayo bukas ng 9am sa conference room.',
  'Good morning po! Paalala lang po na deadline ng project sa Biyernes.',
  'Sir, nasa lobby na po ako. Hintayin ko na lang po kayo dito.',
  'Pasensya na po late ako, sobrang traffic sa EDSA.',
  'Kumain ka na ba? Sabay na tayo mag-lunch mamaya.',
  'Anong oras tayo magkikita? Mga 3pm ok ba sayo?',
  'Nasaan na yung susi ng motor? Hindi ko makita.',
  'Paki-check naman kung naka-lock yung gate bago ka umalis.',
  'Day off ko bukas, punta tayo sa palengke ng maaga.',
  'Sorry di ako nakapunta kagabi, sumama pakiramdam ko.',
  'Musta ka na? Tagal na nating di nagkikita. Kape tayo minsan.',
  'Congrats sa bagong trabaho mo! Proud kami sayo.',
  'Nakita ko na yung bahay na sinasabi mo, ang ganda nga.',
  'Pwede bang palitan ng Huwebes yung schedule natin?',
  'Ok na ba yung aircon? Dumating na ba yung technician?',
  'Paki-forward naman yung picture ng resibo para sa liquidation.',
  'Salamat sa tulong mo kahapon, laking bagay talaga.',
  'Inaantok na ako, bukas na lang tayo mag-usap. Good night!',
  'Your package from Lazada is out for delivery today. Please prepare exact amount for COD.',
  'Hi! Si Kuya rider po ito, nasa labas na po ako ng gate niyo para sa parcel.',
  'Your appointment at St. Luke\'s is confirmed for Monday 10:00 AM. Please arrive 15 minutes early.',
  'Paalala: Ang inyong bill sa Meralco para sa buwang ito ay P2,345.50. Due date: Oktubre 20.',
  'You have received P500.00 from JUAN D. via GCash. Your new balance is P1,250.00.',
  'You have sent P1,000.00 to MARIA S. Ref No. 1234567890. Thank you for using GCash.',
  'Thank you for your payment of P1,599.00 to PLDT. Your account is now updated.',
  'Your BDO credit card statement is now available. Total amount due: P8,420.00.',
  'Hi! Your Grab ride is arriving in 3 minutes. Look for a white Vios, plate ABC 1234.',
  'Ang inyong order ay naihatid na. Salamat sa pagbili sa Shopee!',
  'Reminder: Your dental cleaning is scheduled tomorrow at 2PM. Reply YES to confirm.',
  'Brgy. advisory: Walang tubig bukas mula 8AM hanggang 5PM dahil sa maintenance.',
  'PAGASA: Signal No. 1 sa Metro Manila. Maghanda at mag-ingat ang lahat.',
  'Class suspended bukas dahil sa bagyo. Stay safe everyone.',
  'Ang inyong SSS contribution para sa buwang ito ay naitala na.',
  'Na-renew na po yung lisensya ko, ang bilis lang pala sa LTO ngayon.',
  'Kain tayo sa bahay mamaya, may handaan para sa binyag ni baby.',
  'Pupunta kami sa simbahan ng 7am, sama ka?',
  'Mag-ingat ka sa pag-uwi, madilim na sa kanto.',
  'Na-miss kita! Kailan ka uuwi dito sa Pilipinas?',
  'Ate, nagpadala na ako sa Palawan para sa enrollment ni Ana. Pakikuha na lang.',
  'Ma, ito yung bagong number ko ha, nawala yung luma kong SIM. Tawag ako mamaya para sabihin kung paano.',
  'Okay lang ako dito, wag kayong mag-alala. Busy lang sa trabaho.',
  'Pa, nasira yung gripo sa CR. Pwede mo bang ayusin pag-uwi mo?',
  'Grabe ang init ngayon! Inom kayo ng maraming tubig.',
  'Nanalo ang Ginebra kagabi! Ang galing ng laro.',
  'Napanood mo na yung bagong episode? Ang ganda ng ending.',
  'Bili ka ng pandesal pag-uwi mo, ubos na dito.',
  'Hi Ma\'am, ito po yung tutor ni Miguel. Tapos na po kami sa lesson ngayon.',
  'Good evening po, magpapa-reserve po sana ako ng table for 6 sa Sabado.',
  'Hello, is the apartment still available? Pwede po ba mag-viewing bukas?',
  'Thank you po sa order! I-ship na po namin bukas ng umaga.',
  'Your OTP for BPI Online is 482913. Do not share this code with anyone, including BPI employees.',
  'Your GCash authentication code is 551204. Never share your code with anyone.',
  'Your verification code for Shopee is 739201. It expires in 5 minutes.',
  'Hello, ito yung landlord. Paalala lang na due na ang renta sa katapusan.',
  'Sir, ready na po yung kotse niyo sa casa. Pwede na po kunin.',
  'Nasa ospital si Lolo, pero okay na siya. Bisita tayo bukas ng hapon.',
  'Libre ako bukas, tara mag-mall tayo.',
  'Ang galing mo kanina sa presentation! Congrats!',
];
